version: "3.8"
services:
  db:
    container_name: whooks-db
    image: pingcap/tidb:v8.5.7
    restart: always
    ports:
      - "3306:4000"
      - "10080:10080"
    volumes:
      - db_data:/tmp/tidb

  redis:
    container_name: whooks-redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  bullstudio:
    image: emirce/bullstudio
    ports:
      - "5000:4000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

volumes:
  db_data:
  redis_data:
